FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY node_agent node_agent
ENTRYPOINT ["python", "-m", "node_agent.agent"]
CMD ["${NODE_ID}"]
