version: "3.9"
services:
  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
  controller:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    environment:
      - MQTT_HOST=mqtt
    ports:
      - "8000:8000"
  node1:
    build:
      context: .
      dockerfile: Dockerfile.agent
    depends_on:
      - mqtt
    environment:
      - NODE_ID=node1
      - MQTT_HOST=mqtt
