name: CI

on:
  push:
    branches: [ main, work ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build test image
        run: docker compose build tests
      - name: Run tests
        run: docker compose run --rm tests
